# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choroba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choroba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arche.Choroba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Odp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpowiedz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzajOdpowiedzi', models.CharField(choices=[('TF', 'Prawda albo fa\u0142sz'), ('5S', '5-stopniowa')], max_length=2)),
                ('tresc', models.TextField()),
                ('numer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zestaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasyfikacja', models.CharField(choices=[('ICD-10', 'ICD-10'), ('DSM-IV', 'DSM-IV')], max_length=6)),
                ('choroba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arche.Choroba')),
            ],
        ),
        migrations.AddField(
            model_name='pytanie',
            name='zestaw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arche.Zestaw'),
        ),
        migrations.AddField(
            model_name='odp',
            name='pytanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arche.Pytanie'),
        ),
        migrations.AddField(
            model_name='odp',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arche.Quiz'),
        ),
    ]
