# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 19:48
from __future__ import unicode_literals

import arche.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularzChceZmianyHasla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30, validators=[arche.models.validate_password])),
            ],
        ),
    ]
